on:
  push:
    branches:
      - main
  pull_request:

env:
  HOME: /home/charlie
  OPAMYES: true
  OPAMJOBS: 2

jobs:
  joc:
    name: Check JoC-Style EC Examples
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/easycrypt/ec-build-box:release
    strategy:
      fail-fast: false
      matrix:
        target: [common-joc, prf-joc, prg-joc]
    steps:
    - uses: actions/checkout@v4
    - name: Install and Setup EasyCrypt
      run: |
        opam install --deps-only --depext-only --confirm-level=unsafe-yes easycrypt
        opam install --deps-only easycrypt
        opam install easycrypt
        rm -f ~/.why3.conf
        opam exec -- easycrypt why3config -why3 ~/.why3.conf
    - name: Check JoC-style proof ${{ matrix.target }}
      env:
        TARGET: ${{ matrix.target }}
      run: opam exec -- easycrypt runtest easycrypt.config

  std:
    name: Check idiomatic EC Examples
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/easycrypt/ec-build-box:release
    strategy:
      fail-fast: false
      matrix:
        target: [prg-pure, prg-modular]
    steps:
    - uses: actions/checkout@v4
    - name: Install and Setup EasyCrypt
      run: |
        opam install --deps-only --depext-only --confirm-level=unsafe-yes easycrypt
        opam install --deps-only easycrypt
        opam install easycrypt
        rm -f ~/.why3.conf
        opam exec -- easycrypt why3config -why3 ~/.why3.conf
    - name: Check idiomatic proof ${{ matrix.target }}
      env:
        TARGET: ${{ matrix.target }}
      run: opam exec -- easycrypt runtest easycrypt.config ${{ matrix.target }}

